#pragma config(Sensor, dgtl1,  touchSensor,    sensorTouch)
#pragma config(Sensor, dgtl2,  bumperSensor,   sensorTouch)
#pragma config(Motor,  port1,           leftMotor,     tmotorVex393_HBridge, openLoop, reversed)
#pragma config(Motor,  port2,           RclawMotor,    tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port3,           LclawMotor,    tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port4,           armMotor,      tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port10,          rightMotor,    tmotorVex269_HBridge, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*---------------------------------------------------------------------------*/
/*                                                                           */
/*        Description: Competition template for VEX EDR                      */
/*                                                                           */
/*---------------------------------------------------------------------------*/

// This code is for the VEX cortex platform
#pragma platform(VEX2)

// Select Download method as "competition"
#pragma competitionControl(Competition)

//Main competition background code...do not modify!
#include "Vex_Competition_Includes.c"

#define MIN(a,b) (((a)<(b))?(a):(b))
#define MAX(a,b) (((a)>(b))?(a):(b))


/*---------------------------------------------------------------------------*/
/*                          Pre-Autonomous Functions                         */
/*                                                                           */
/*  You may want to perform some actions before the competition starts.      */
/*  Do them in the following function.  You must return from this function   */
/*  or the autonomous and usercontrol tasks will not be started.  This       */
/*  function is only called once after the cortex has been powered on and    */
/*  not every time that the robot is disabled.                               */
/*---------------------------------------------------------------------------*/

void pre_auton()
{
  // Set bStopTasksBetweenModes to false if you want to keep user created tasks
  // running between Autonomous and Driver controlled modes. You will need to
  // manage all user created tasks if set to false.
  bStopTasksBetweenModes = true;

	// Set bDisplayCompetitionStatusOnLcd to false if you don't want the LCD
	// used by the competition include file, for example, you might want
	// to display your team name on the LCD in this function.
	// bDisplayCompetitionStatusOnLcd = false;

  // All activities that occur before the competition starts
  // Example: clearing encoders, setting servo positions, ...
}

/*---------------------------------------------------------------------------*/
/*                                                                           */
/*                              Autonomous Task                              */
/*                                                                           */
/*  This task is used to control your robot during the autonomous phase of   */
/*  a VEX Competition.                                                       */
/*                                                                           */
/*  You must modify the code to add your own robot specific commands here.   */
/*---------------------------------------------------------------------------*/

task autonomous()
{
	while(SensorValue(touchSensor) == 0 || SensorValue(bumperSensor) == 0)		// Loop while robot's bumper/touch sensor isn't pressed in
	{
		motor[rightMotor] = 63;			            // Motor on port2 is run at half (63) power forward
		motor[leftMotor]  = -63;			            // Motor on port3 is run at half (63) power forward
	}

	motor[rightMotor] = -63;			            // Motor on port2 is run at half (63) power backward
	motor[leftMotor]  = 63;			            // Motor on port3 is run at half (63) power backward
	motor[RclawMotor] = -127;
	motor[LclawMotor] = -127;
	wait1Msec(500);				                // Robot runs previous code for 500 milliseconds before moving on
	motor[rightMotor] = 0;			            // Motor on port2 is run at half (63) power backward
	motor[leftMotor]  = 0;			            // Motor on port3 is run at half (63) power backward
	motor[RclawMotor] = 0;
	motor[LclawMotor] = 0;
}

/*---------------------------------------------------------------------------*/
/*                                                                           */
/*                              User Control Task                            */
/*                                                                           */
/*  This task is used to control your robot during the user control phase of */
/*  a VEX Competition.                                                       */
/*                                                                           */
/*  You must modify the code to add your own robot specific commands here.   */
/*---------------------------------------------------------------------------*/


// some functions / some functions for interpolating speeds
bool inDeadZone(float value1, float value2, float deadZone){ // does as name says
	return ((abs(value1 - value2) < deadZone) ? (true) : (false));
}

void goToTarget(float target, short nam, float *start_vel, float *prev_target){
	float vel = motor[nam]; // get speed of motor

	if (~inDeadZone(target, *prev_target, .5)){ // if the wanted position is outside of the last position by
		*start_vel = vel;													//a factor of .5 it will make a new target, gets rid of wiggle
		*prev_target = target;
	}

	float cMap = (vel-*start_vel)/(target-*start_vel); // maps everything to a scale of 0 to 1
	float acl = cMap*(1-cMap);												 // finds the currect position of the aceleration depending on the scale
	if (acl == 0 && target != vel){
		acl = .02;																			 // at the start makes sure its not 0 or it will never start
	}
	float next_vel = vel + acl*( target-*start_vel);

	next_vel = MAX(-127.0, next_vel);                  // constrains to min max speeds of motors
	next_vel = MIN(127.0, next_vel);
	motor[nam] = next_vel;                             // sets speed to motor
}



task usercontrol()
{
	int dt = 10;  // in miliseconds deltatime between loops

	float Lstart_vel = 0;
	float Lprev_target = 0;
	float Rstart_vel = 0;
	float Rprev_target = 0;
	float slower_modeoffset = 4;

	float armStart_vel = 0;
	float armPrev_vel = 0;

	float motor_arm_speed = 80;


	while (true){
		// driving motors
		float left_target = vexRT[Ch2] + (vexRT[Ch3] / slower_modeoffset);  // left moter forward back
		float right_target = vexRT[Ch2] + (vexRT[Ch3] / slower_modeoffset);  // right moter forward back

		left_target = left_target + vexRT[Ch1] + (vexRT[Ch4] / slower_modeoffset);  // left moter turn offset
		right_target = right_target - vexRT[Ch1] - (vexRT[Ch4] / slower_modeoffset);  // right motar turn offset

		goToTarget(left_target,  leftMotor,  &Lstart_vel, &Lprev_target);
		goToTarget(right_target, rightMotor, &Rstart_vel, &Rprev_target);


		// raise / lower arm
		if(vexRT[Btn6U] == 1)       	//If Button 6U is pressed...
		{
			goToTarget(-127,  armMotor,  &armStart_vel, &armPrev_vel);  	//...raise the arm.
		}
		else if(vexRT[Btn6D] == 1)  	//Else, if button 6D is pressed...
		{
			goToTarget(127,  armMotor,  &armStart_vel, &armPrev_vel);    //...lower the arm.
		} else {
			goToTarget(0,  armMotor,  &armStart_vel, &armPrev_vel);
		}


		// do claw spinnings
		if(vexRT[Btn5U] == 1)       	//If button 5U is pressed...
		{
			   	//spin one way.
			motor[RclawMotor] = motor_arm_speed;
			motor[LclawMotor] = motor_arm_speed;
		}
		else if(vexRT[Btn5D] == 1)  	//Else, if button 5D is pressed...
		{
			  	//spin the other way.
			motor[RclawMotor] = -motor_arm_speed;
			motor[LclawMotor] = -motor_arm_speed;
		} else {
			motor[RclawMotor] = 0;
			motor[LclawMotor] = 0;
		}

		wait1Msec(dt);
	}
}
