#pragma config(Sensor, dgtl1,  touchSensor,    sensorTouch)
#pragma config(Sensor, dgtl2,  bumperSensor,   sensorTouch)
#pragma config(Motor,  port1,           leftMotor,     tmotorVex393_HBridge, openLoop, reversed)
#pragma config(Motor,  port2,           RclawMotor,    tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port3,           LclawMotor,    tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port4,           armMotor,      tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port10,          rightMotor,    tmotorVex269_HBridge, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*---------------------------------------------------------------------------*/
/*                                                                           */
/*        Description: Competition template for VEX EDR                      */
/*                                                                           */
/*---------------------------------------------------------------------------*/

// This code is for the VEX cortex platform
#pragma platform(VEX2)

// Select Download method as "competition"
#pragma competitionControl(Competition)

//Main competition background code...do not modify!
#include "Vex_Competition_Includes.c"

/*---------------------------------------------------------------------------*/
/*                          Pre-Autonomous Functions                         */
/*                                                                           */
/*  You may want to perform some actions before the competition starts.      */
/*  Do them in the following function.  You must return from this function   */
/*  or the autonomous and usercontrol tasks will not be started.  This       */
/*  function is only called once after the cortex has been powered on and    */
/*  not every time that the robot is disabled.                               */
/*---------------------------------------------------------------------------*/

void pre_auton()
{
  // Set bStopTasksBetweenModes to false if you want to keep user created tasks
  // running between Autonomous and Driver controlled modes. You will need to
  // manage all user created tasks if set to false.
  bStopTasksBetweenModes = true;

	// Set bDisplayCompetitionStatusOnLcd to false if you don't want the LCD
	// used by the competition include file, for example, you might want
	// to display your team name on the LCD in this function.
	// bDisplayCompetitionStatusOnLcd = false;

  // All activities that occur before the competition starts
  // Example: clearing encoders, setting servo positions, ...
}

/*---------------------------------------------------------------------------*/
/*                                                                           */
/*                              Autonomous Task                              */
/*                                                                           */
/*  This task is used to control your robot during the autonomous phase of   */
/*  a VEX Competition.                                                       */
/*                                                                           */
/*  You must modify the code to add your own robot specific commands here.   */
/*---------------------------------------------------------------------------*/

task autonomous()
{
	while(SensorValue(touchSensor) == 0 || SensorValue(bumperSensor) == 0)		// Loop while robot's bumper/touch sensor isn't pressed in
	{
		motor[rightMotor] = 63;			            // Motor on port2 is run at half (63) power forward
		motor[leftMotor]  = -63;			            // Motor on port3 is run at half (63) power forward
	}

	motor[rightMotor] = -63;			            // Motor on port2 is run at half (63) power backward
	motor[leftMotor]  = 63;			            // Motor on port3 is run at half (63) power backward
	motor[RclawMotor] = -127;
	motor[LclawMotor] = -127;
	wait1Msec(500);				                // Robot runs previous code for 500 milliseconds before moving on
	motor[rightMotor] = 0;			            // Motor on port2 is run at half (63) power backward
	motor[leftMotor]  = 0;			            // Motor on port3 is run at half (63) power backward
	motor[RclawMotor] = 0;
	motor[LclawMotor] = 0;
}

/*---------------------------------------------------------------------------*/
/*                                                                           */
/*                              User Control Task                            */
/*                                                                           */
/*  This task is used to control your robot during the user control phase of */
/*  a VEX Competition.                                                       */
/*                                                                           */
/*  You must modify the code to add your own robot specific commands here.   */
/*---------------------------------------------------------------------------*/

task usercontrol()
{

	while(1 == 1)
	{
		motor[leftMotor]  = (vexRT[Ch1] - vexRT[Ch2]);  // (y + x)/2
		motor[rightMotor] = (vexRT[Ch1] + vexRT[Ch2]);  // (y - x)/2

// Raise, lower or do not move arm
		if(vexRT[Btn5U] == 1)       	//If button 5U is pressed...
		{
			//motor[armMotor] = 127;    	//...raise the arm.
			motor[RclawMotor] = 80
			motor[LclawMotor] = 80;
		}
		else if(vexRT[Btn5D] == 1)  	//Else, if button 5D is pressed...
		{
			//motor[armMotor] = -127;   	//...lower the arm.
			motor[RclawMotor] = -80;
			motor[LclawMotor] = -80;
		} else {
			motor[RclawMotor] = 0;
			motor[LclawMotor] = 0;
		}


// Open, close or do not more claw
		if(vexRT[Btn6U] == 1)       	//If Button 6U is pressed...
		{
			motor[armMotor] = -127;    	//...raise the arm.
			//motor[RclawMotor] = 60;
		}
		else if(vexRT[Btn6D] == 1)  	//Else, if button 6D is pressed...
		{
			motor[armMotor] = 127;   	//...lower the arm.
			//motor[RclawMotor] = -60;
		} else {
			motor[armMotor] = 0;
		}

	}
}
